# Generated by Django 5.0.3 on 2024-03-21 16:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_rename_todo_todoitems'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoItems',
            new_name='TodoItem',
        ),
    ]
